### ISSUE TITLE
Hello. Can I get a compiled exe for this file. I need it so badly and I cannot find anywhere.

### ISSUE THREAD

**Issue by aimyafi** [LongSoft/PMPatch#4]
I need it to unlock uefi in one old dell inspiron n4100. I only have instructions using pmpatch. please please give me an exe.

**Comment by aimyafi** [comment]
I need it to unlock uefi in one old dell inspiron n4100. I only have instructions using pmpatch. please please give me an exe.

**Comment by NikolajSchlej** [comment]
The tool is severely outdated and not supported anymore. Try UEFIPatch from UEFITool repo instead.

**Comment by aimyafi** [comment]
I got the BIOS in exe format which cannot be patched with UEFITool. That's why I was really hoping rhis tool could help. Thanks anyway.

**Comment by aimyafi** [comment]
> The tool is severely outdated and not supported anymore. Try UEFIPatch from UEFITool repo instead.

I got the BIOS in exe format which cannot be patched with UEFITool. That's why I was really hoping rhis tool could help. Thanks anyway.

**Comment by NikolajSchlej** [comment]
It will certainly not help, because it's a very basic patcher for ROM images only.
